spring:
  datasource:
    url: jdbc:mysql://localhost:3306/TeamMonDB
    username: root
    password: ysmjk_0304
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
  sql:
    init:
      platform: mysql
      mode: always