debug: false
management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    com.teammatching.demo: debug
    org.springframework.web.servlet: debug
    org.hibernate.type.descriptor.sql: trace

spring:
  profiles:
    include: jwt
  datasource:
    url: jdbc:mysql://team-matching-be-yjsmk0902.koyeb.app:8000/teamMatching
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
  sql:
    init:
      mode: always

      #Swagger Springdoc-UI Configuration
springdoc:
  packages-to-scan: com.teammatching.demo
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8
  swagger-ui:
    path: swagger-ui.html       #Swagger UI 경로 -> localhost:8000/swagger-ui.html
    tags-sorter: method         #alpha: 알파벳 순 태그 정렬 / method: HTTP Method 순 정렬
    operations-sorter: method   #alpha: 알파벳 순 태그 정렬 / method: HTTP Method 순 정렬
  api-docs:
    path: /v1/api-docs
    groups:
      enabled: true
  cache:
    disabled: true
  show-login-endpoint: true
