spring:
  datasource:
    url: jdbc:mysql://3.34.178.228:3306/TeamMonDB
    username: luke
    password: 04870325
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
  sql:
    init:
      platform: mysql
      mode: always